### ISSUE TITLE
List all the colors we use

### ISSUE THREAD

**Issue by annabialas** [GovLab/styleguide2#34]
"Get rid of green and red we never use anywhere" -- @chrswng

**Comment by chrswng** [comment]
- [x] Change MRFP to Multistate Registration and Filing Portal
- [x] Change Open Data Symposium 2016 to Open Data Research Symposium
- [x] Split Up Zika Section to Smarter Crowdsourcing, Zika, and Anti-Corruption add #435B6A and #86AE51

**Comment by annabialas** [comment]
BUSTED
